package com.orchexpay.walletledger.dtos;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateUserRequest {

    @NotBlank(message = "Username is required")
    @Size(min = 2, max = 255)
    private String username;

    @NotBlank(message = "Password is required")
    @Size(min = 8, message = "Password must be at least 8 characters")
    private String password;

    @NotEmpty(message = "At least one role is required")
    private Set<String> roles;  // MERCHANT, ADMIN, SYSTEM (VENDOR is added via POST /merchants/{merchantId}/vendors)

    /** Required when role is MERCHANT: currency for the created MAIN and ESCROW wallets (e.g. INR). Ignored for ADMIN/SYSTEM. */
    private String currencyCode;

    // merchantId is generated by backend when role is MERCHANT; not accepted from client
}
